name: Build and push docker image

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_ACCOUNT: gelugu
  APP_NAME: newsletter
  VERSION: 0.1.0

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{env.VERSION}} -p ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build the Docker image
        run: docker build -t ${{env.VERSION}}/${{env.VERSION}}:${{env.VERSION}} -f Dockerfile .
      - name: Push the Docker image
        run: docker push ${{env.VERSION}}/${{env.VERSION}}:${{env.VERSION}}
